language: node_js
node_js: stable
branch:
  only:
  - master
before_install:
- npm install -g gitbook-cli
install:
- npm install
script:
- gitbook build . ./docs
after_success:
- git init
- git config --global user.name 'shaodahong'
- git config --global user.email 'darryshaw@gmail.com'
- git add .
- git commit -m "generate static resources, triggerd by travis ci"
- git push --force "https://wangming1993:${REPO_TOKEN}@${GH_REF}" master:master
env:
  global:
    - GH_REF: github.com/shaodahong/web-topic.git